// Defines Tabla OPERAC.PUESTOS
//
// schema operac, old;
// dbtable APUESTOS;
//
// old = CurrentSchema();
// operac = OpenSchema("operac", IO_EABORT);
// SwitchToSchema(old);
//
// APUESTOS = CreateAlias(operac|PUESTOS);
//
// DeleteAlias(APUESTOS);

# define APUESTOS_CLIENTE  AlFld(APUESTOS, operac|PUESTOS_CLIENTE)
# define APUESTOS_OBJET    AlFld(APUESTOS, operac|PUESTOS_OBJET)
# define APUESTOS_TIPPTO   AlFld(APUESTOS, operac|PUESTOS_TIPPTO)
# define APUESTOS_PUESTO   AlFld(APUESTOS, operac|PUESTOS_PUESTO)
# define APUESTOS_HINICIO  AlFld(APUESTOS, operac|PUESTOS_HINICIO)
# define APUESTOS_HFINAL   AlFld(APUESTOS, operac|PUESTOS_HFINAL)
# define APUESTOS_DIA1     AlFld(APUESTOS, operac|PUESTOS_DIA1)
# define APUESTOS_DIA2     AlFld(APUESTOS, operac|PUESTOS_DIA2)
# define APUESTOS_DIA3     AlFld(APUESTOS, operac|PUESTOS_DIA3)
# define APUESTOS_DIA4     AlFld(APUESTOS, operac|PUESTOS_DIA4)
# define APUESTOS_DIA5     AlFld(APUESTOS, operac|PUESTOS_DIA5)
# define APUESTOS_DIA6     AlFld(APUESTOS, operac|PUESTOS_DIA6)
# define APUESTOS_DIA7     AlFld(APUESTOS, operac|PUESTOS_DIA7)
# define APUESTOS_REGIM    AlFld(APUESTOS, operac|PUESTOS_REGIM)
# define APUESTOS_CODINT   AlFld(APUESTOS, operac|PUESTOS_CODINT)
# define APUESTOS_CANTVIG  AlFld(APUESTOS, operac|PUESTOS_CANTVIG)
# define APUESTOS_VIGI     AlFld(APUESTOS, operac|PUESTOS_VIGI)
# define APUESTOS_CDATE    AlFld(APUESTOS, operac|PUESTOS_CDATE)
# define APUESTOS_CTIME    AlFld(APUESTOS, operac|PUESTOS_CTIME)
# define APUESTOS_CUID     AlFld(APUESTOS, operac|PUESTOS_CUID)
# define APUESTOS_MDATE    AlFld(APUESTOS, operac|PUESTOS_MDATE)
# define APUESTOS_MTIME    AlFld(APUESTOS, operac|PUESTOS_MTIME)
# define APUESTOS_MUID     AlFld(APUESTOS, operac|PUESTOS_MUID)
# define APUESTOS_CODFREC  AlFld(APUESTOS, operac|PUESTOS_CODFREC)
# define APUESTOS_HORAPT   AlFld(APUESTOS, operac|PUESTOS_HORAPT)
# define APUESTOS_FINICIO  AlFld(APUESTOS, operac|PUESTOS_FINICIO)
# define APUESTOS_FFINAL   AlFld(APUESTOS, operac|PUESTOS_FFINAL)
# define APUESTOSbyCLIENTE AlInd(APUESTOS, operac|PUESTOSbyCLIENTE)
# define APUESTOSbyPUESTO  AlInd(APUESTOS, operac|PUESTOSbyPUESTO)

// Defines Tabla OPERAC.ASIG

# define AASIG_EMP        AlFld(AASIG, operac|ASIG_EMP)
# define AASIG_CLIENTE    AlFld(AASIG, operac|ASIG_CLIENTE)
# define AASIG_OBJETIVO   AlFld(AASIG, operac|ASIG_OBJETIVO)
# define AASIG_PTOSER     AlFld(AASIG, operac|ASIG_PTOSER)
# define AASIG_PUESTO     AlFld(AASIG, operac|ASIG_PUESTO)
# define AASIG_NROLEG     AlFld(AASIG, operac|ASIG_NROLEG)
# define AASIG_VIGIL      AlFld(AASIG, operac|ASIG_VIGIL)
# define AASIG_EFECT      AlFld(AASIG, operac|ASIG_EFECT)
# define AASIG_FECASIG    AlFld(AASIG, operac|ASIG_FECASIG)
# define AASIG_HSENT      AlFld(AASIG, operac|ASIG_HSENT)
# define AASIG_HSSAL      AlFld(AASIG, operac|ASIG_HSSAL)
# define AASIG_DIA1       AlFld(AASIG, operac|ASIG_DIA1)
# define AASIG_DIA2       AlFld(AASIG, operac|ASIG_DIA2)
# define AASIG_DIA3       AlFld(AASIG, operac|ASIG_DIA3)
# define AASIG_DIA4       AlFld(AASIG, operac|ASIG_DIA4)
# define AASIG_DIA5       AlFld(AASIG, operac|ASIG_DIA5)
# define AASIG_DIA6       AlFld(AASIG, operac|ASIG_DIA6)
# define AASIG_DIA7       AlFld(AASIG, operac|ASIG_DIA7)
# define AASIG_REEMPL     AlFld(AASIG, operac|ASIG_REEMPL)
# define AASIG_FFRANCO    AlFld(AASIG, operac|ASIG_FFRANCO)
# define AASIG_REGIM      AlFld(AASIG, operac|ASIG_REGIM)
# define AASIG_FECHAS     AlFld(AASIG, operac|ASIG_FECHAS)
# define AASIG_FECBAJ     AlFld(AASIG, operac|ASIG_FECBAJ)
# define AASIG_NUMFRAN    AlFld(AASIG, operac|ASIG_NUMFRAN)
# define AASIG_FRANCERO   AlFld(AASIG, operac|ASIG_FRANCERO)
# define AASIG_NROINT     AlFld(AASIG, operac|ASIG_NROINT)
# define AASIG_TIPODIA    AlFld(AASIG, operac|ASIG_TIPODIA)
# define AASIG_CODROL     AlFld(AASIG, operac|ASIG_CODROL)
# define AASIG_FILA       AlFld(AASIG, operac|ASIG_FILA)
# define AASIG_COLUM      AlFld(AASIG, operac|ASIG_COLUM)
# define AASIG_REGPTO     AlFld(AASIG, operac|ASIG_REGPTO)
# define AASIGbyEMP       AlInd(AASIG, operac|ASIGbyEMP)
# define AASIGbyFECHA     AlInd(AASIG, operac|ASIGbyFECHA)
# define AASIGbyNROLEG    AlInd(AASIG, operac|ASIGbyNROLEG)
# define AASIGbyLEGFEC    AlInd(AASIG, operac|ASIGbyLEGFEC)
# define AASIGbyPUESTO    AlInd(AASIG, operac|ASIGbyPUESTO)

// Defines Tabla OPERAC.PARTE
# define APARTE_EMP       AlFld(APARTE, operac|PARTE_EMP)
# define APARTE_CLIENTE   AlFld(APARTE, operac|PARTE_CLIENTE)
# define APARTE_OBJETIVO  AlFld(APARTE, operac|PARTE_OBJETIVO)
# define APARTE_DIA       AlFld(APARTE, operac|PARTE_DIA)
# define APARTE_NROLEG    AlFld(APARTE, operac|PARTE_NROLEG)
# define APARTE_HORAENT   AlFld(APARTE, operac|PARTE_HORAENT)
# define APARTE_HORASAL   AlFld(APARTE, operac|PARTE_HORASAL)
# define APARTE_CONFIR    AlFld(APARTE, operac|PARTE_CONFIR)
# define APARTE_HSNOR     AlFld(APARTE, operac|PARTE_HSNOR)
# define APARTE_HS50      AlFld(APARTE, operac|PARTE_HS50)
# define APARTE_HS100F    AlFld(APARTE, operac|PARTE_HS100F)
# define APARTE_HS100FE   AlFld(APARTE, operac|PARTE_HS100FE)
# define APARTE_CONDIC    AlFld(APARTE, operac|PARTE_CONDIC)
# define APARTE_CONFEX    AlFld(APARTE, operac|PARTE_CONFEX)
# define APARTE_PTOSER    AlFld(APARTE, operac|PARTE_PTOSER)
# define APARTE_PUESTO    AlFld(APARTE, operac|PARTE_PUESTO)
# define APARTE_NROINT    AlFld(APARTE, operac|PARTE_NROINT)
# define APARTE_CODAUS    AlFld(APARTE, operac|PARTE_CODAUS)
# define APARTEbyEMP      AlInd(APARTE, operac|PARTEbyEMP)
# define APARTEbyLEG      AlInd(APARTE, operac|PARTEbyLEG)
# define APARTEbyEMPLE    AlInd(APARTE, operac|PARTEbyEMPLE)
# define APARTEbyPUESTO   AlInd(APARTE, operac|PARTEbyPUESTO)
# define APARTEbyDIA      AlInd(APARTE, operac|PARTEbyDIA)

// Defines Tabla FRECUEN
#define AFRECUEN_CODFREC  AlFld(AFRECUEN, operac|FRECUEN_CODFREC)
#define AFRECUEN_DESCRIP  AlFld(AFRECUEN, operac|FRECUEN_DESCRIP)
#define AFRECUENbyCODFREC AlInd(AFRECUEN, operac|FRECUENbyCODFREC)

// Defines Tabla VACAC
# define AVACAC_EMP       AlFld(AVACAC, operac|VACAC_EMP)
# define AVACAC_NROLEG    AlFld(AVACAC, operac|VACAC_NROLEG)
# define AVACAC_CANTDIAS  AlFld(AVACAC, operac|VACAC_CANTDIAS)
# define AVACAC_MODULO    AlFld(AVACAC, operac|VACAC_MODULO)
# define AVACAC_FDESDE    AlFld(AVACAC, operac|VACAC_FDESDE)
# define AVACAC_FHASTA    AlFld(AVACAC, operac|VACAC_FHASTA)
# define AVACAC_FPASE     AlFld(AVACAC, operac|VACAC_FPASE)
# define AVACACbyEMP      AlInd(AVACAC, operac|VACACbyEMP)


// Defines Tabla ASIGH
# define AASIGH_EMP       AlFld(AASIGH, operac|ASIGH_EMP)
# define AASIGH_CLIENTE   AlFld(AASIGH, operac|ASIGH_CLIENTE)
# define AASIGH_OBJETIVO  AlFld(AASIGH, operac|ASIGH_OBJETIVO)
# define AASIGH_PTOSER    AlFld(AASIGH, operac|ASIGH_PTOSER)
# define AASIGH_PUESTO    AlFld(AASIGH, operac|ASIGH_PUESTO)
# define AASIGH_NROLEG    AlFld(AASIGH, operac|ASIGH_NROLEG)
# define AASIGH_VIGIL     AlFld(AASIGH, operac|ASIGH_VIGIL)
# define AASIGH_EFECT     AlFld(AASIGH, operac|ASIGH_EFECT)
# define AASIGH_FECALT    AlFld(AASIGH, operac|ASIGH_FECALT)
# define AASIGH_FECBAJ    AlFld(AASIGH, operac|ASIGH_FECBAJ)
# define AASIGH_HSENT     AlFld(AASIGH, operac|ASIGH_HSENT)
# define AASIGH_HSSAL     AlFld(AASIGH, operac|ASIGH_HSSAL)
# define AASIGH_DIA1      AlFld(AASIGH, operac|ASIGH_DIA1)
# define AASIGH_DIA2      AlFld(AASIGH, operac|ASIGH_DIA2)
# define AASIGH_DIA3      AlFld(AASIGH, operac|ASIGH_DIA3)
# define AASIGH_DIA4      AlFld(AASIGH, operac|ASIGH_DIA4)
# define AASIGH_DIA5      AlFld(AASIGH, operac|ASIGH_DIA5)
# define AASIGH_DIA6      AlFld(AASIGH, operac|ASIGH_DIA6)
# define AASIGH_DIA7      AlFld(AASIGH, operac|ASIGH_DIA7)
# define AASIGH_MOTIVO    AlFld(AASIGH, operac|ASIGH_MOTIVO)
# define AASIGH_REEMPL    AlFld(AASIGH, operac|ASIGH_REEMPL)
# define AASIGH_REGIM     AlFld(AASIGH, operac|ASIGH_REGIM)
# define AASIGH_FECHAS    AlFld(AASIGH, operac|ASIGH_FECHAS)
# define AASIGH_CDATE     AlFld(AASIGH, operac|ASIGH_CDATE)
# define AASIGH_CTIME     AlFld(AASIGH, operac|ASIGH_CTIME)
# define AASIGH_CUID      AlFld(AASIGH, operac|ASIGH_CUID)
# define AASIGH_MDATE     AlFld(AASIGH, operac|ASIGH_MDATE)
# define AASIGH_MTIME     AlFld(AASIGH, operac|ASIGH_MTIME)
# define AASIGH_MUID      AlFld(AASIGH, operac|ASIGH_MUID)
# define AASIGH_FFRANCO   AlInd(AASIGH, operac|ASIGH_FFRANCO)
# define AASIGH_NUMFRAN   AlFld(AASIGH, operac|ASIGH_NUMFRAN)
# define AASIGH_FRANCERO  AlFld(AASIGH, operac|ASIGH_FRANCERO)
# define AASIGH_NROINT    AlFld(AASIGH, operac|ASIGH_NROINT)
# define AASIGH_CODROL    AlFld(AASIGH, operac|ASIGH_CODROL)
# define AASIGH_FILA      AlFld(AASIGH, operac|ASIGH_FILA)
# define AASIGH_COLUM     AlFld(AASIGH, operac|ASIGH_COLUM)
# define AASIGH_REGPTO    AlFld(AASIGH, operac|ASIGH_REGPTO)
# define AASIGHbyEMP      AlInd(AASIGH, operac|ASIGHbyEMP)
# define AASIGHbyPUESTO   AlInd(AASIGH, operac|ASIGHbyPUESTO)
# define AASIGHbyNROLEG   AlInd(AASIGH, operac|ASIGHbyNROLEG)
# define AASIGHbyFECHABAJ AlInd(AASIGH, operac|ASIGHbyFECHABAJ)
# define AASIGHbyLEGFEC   AlInd(AASIGH, operac|ASIGHbyLEGFEC)
# define AASIGHbyFECHAALT AlInd(AASIGH, operac|ASIGHbyFECHAALT)

// Defines Tabla OPERAC.RETRO
# define ARETRO_EMP       AlFld(ARETRO, operac|RETRO_EMP)
# define ARETRO_CLIENTE   AlFld(ARETRO, operac|RETRO_CLIENTE)
# define ARETRO_OBJETIVO  AlFld(ARETRO, operac|RETRO_OBJETIVO)
# define ARETRO_DIA       AlFld(ARETRO, operac|RETRO_DIA)
# define ARETRO_FECREG    AlFld(ARETRO, operac|RETRO_FECREG)
# define ARETRO_NROLEG    AlFld(ARETRO, operac|RETRO_NROLEG)
# define ARETRO_HORAENT   AlFld(ARETRO, operac|RETRO_HORAENT)
# define ARETRO_HORASAL   AlFld(ARETRO, operac|RETRO_HORASAL)
# define ARETRO_CONFIR    AlFld(ARETRO, operac|RETRO_CONFIR)
# define ARETRO_HSNOR     AlFld(ARETRO, operac|RETRO_HSNOR)
# define ARETRO_HS50      AlFld(ARETRO, operac|RETRO_HS50)
# define ARETRO_HS100F    AlFld(ARETRO, operac|RETRO_HS100F)
# define ARETRO_HS100FE   AlFld(ARETRO, operac|RETRO_HS100FE)
# define ARETRO_CONDIC    AlFld(ARETRO, operac|RETRO_CONDIC)
# define ARETRO_CONFEX    AlFld(ARETRO, operac|RETRO_CONFEX)
# define ARETRO_PTOSER    AlFld(ARETRO, operac|RETRO_PTOSER)
# define ARETRO_PUESTO    AlFld(ARETRO, operac|RETRO_PUESTO)
# define ARETRO_NROINT    AlFld(ARETRO, operac|RETRO_NROINT)
# define ARETRO_CODAUS    AlFld(ARETRO, operac|RETRO_CODAUS)
# define ARETRO_DHSNOR    AlFld(ARETRO, operac|RETRO_DHSNOR)
# define ARETRO_DHS50     AlFld(ARETRO, operac|RETRO_DHS50)
# define ARETRO_DHS100    AlFld(ARETRO, operac|RETRO_DHS100)
# define ARETRO_DHS100FE  AlFld(ARETRO, operac|RETRO_DHS100FE)
# define ARETRO_LIQDENA   AlFld(ARETRO, operac|RETRO_LIQDENA)
# define ARETRO_LIQFAC    AlFld(ARETRO, operac|RETRO_LIQFAC)
# define ARETRO_ASICBLE   AlFld(ARETRO, operac|RETRO_ASICBLE)
# define ARETRO_NROFAC    AlFld(ARETRO, operac|RETRO_NROFAC)
# define ARETRObyEMP      AlInd(ARETRO, operac|RETRObyEMP)
# define ARETRObyRLEG     AlInd(ARETRO, operac|RETRObyRLEG)
# define ARETRObyREMPLE   AlInd(ARETRO, operac|RETRObyREMPLE)
# define ARETRObyRDIA     AlInd(ARETRO, operac|RETRObyRDIA)
